/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abrir.archivo;

import java.awt.Label;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Pablo
 */
public class ResolverConflictos extends javax.swing.JFrame {
     private XSSFWorkbook ArchivoEX;
     private int filaExcep;
     private int columnaExcep;
     private int hoja;
     private int filaExcel;
     private int columnaExcel;
    
    /**
     * Creates new form ResolverConflictos
     */
    public ResolverConflictos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Correccion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        InfoLinea = new javax.swing.JTextField();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        jLabel3.setText("Informacion Completa:");

        Tipo.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Tipo.setText("Tipo:");

        Correccion.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        Correccion.setToolTipText("");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        InfoLinea.setEditable(false);
        InfoLinea.setBackground(new java.awt.Color(255, 255, 255));
        InfoLinea.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        InfoLinea.setText("jTextField1");
        InfoLinea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tipo)
                        .addGap(29, 29, 29)
                        .addComponent(Correccion, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(InfoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 1469, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo)
                    .addComponent(Correccion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("".equals(Correccion.getText())){
            JOptionPane.showMessageDialog(null, "Rellene la informacion");
        }
        else{
            Excel.getModelo().removeRow(filaExcep);
            Excel.getConflictos().remove(filaExcep);
            switch (Tipo.getText()) {
                case "Autor":
                    columnaExcel=2;
                    break;
                case "Escuela o Unidad":
                    columnaExcel=3;
                    break;
                case "Campus":
                    columnaExcel=4;
                    break;
                case "Universidad":
                    columnaExcel=3;
                    break;
                case "País":
                    columnaExcel=4;
                    break;
                default:
                    throw new AssertionError();
            }

            ArchivoEX.getSheetAt(hoja).getRow(filaExcel-1).getCell(columnaExcel).setCellValue(Correccion.getText());
          //  System.out.println("Aqui");
            dispose();
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    public ResolverConflictos(XSSFWorkbook ArchivoEX, int filaC, int columnaC,int filaExcel,int hoja) {
        initComponents();
        this.ArchivoEX = ArchivoEX;
        this.filaExcep = filaC;
        this.columnaExcep = columnaC;
        this.filaExcel=filaExcel;
        this.hoja=hoja;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResolverConflictos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResolverConflictos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResolverConflictos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResolverConflictos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResolverConflictos().setVisible(true);
            }
        });
    }

    public JTextField getInfoLinea() {
        return InfoLinea;
    }

    public JLabel getTipo() {
        return Tipo;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Correccion;
    private javax.swing.JTextField InfoLinea;
    private javax.swing.JLabel Tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
