/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Procesar.Excel;

import java.awt.Label;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 * En esta clase se visualiza el nombre del Excel seleccionado y se selecciona que tipo de Excel es WoS/ESCI o Scopus 
 * @author Pablo
 * 
 * 
 */
public class TipoArchivoSelec extends javax.swing.JFrame {
    File Archivo;
   
    /**
     * Creates new form vista
     */
    public TipoArchivoSelec() {
        initComponents();
    }
    public TipoArchivoSelec(File f) {
        initComponents();
        Archivo=f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup3 = new javax.swing.ButtonGroup();
        Cancelar = new javax.swing.JButton();
        Inicio = new javax.swing.JButton();
        label1 = new java.awt.Label();
        archSelect = new java.awt.Label();
        rb_Scopus = new javax.swing.JRadioButton();
        rb_WoS = new javax.swing.JRadioButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipo de archivo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 500));
        setLocationByPlatform(true);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Inicio.setText("Iniciar");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label1.setText("Archivo seleccionado:");

        archSelect.setAlignment(java.awt.Label.CENTER);
        archSelect.setBackground(new java.awt.Color(255, 255, 255));
        archSelect.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N

        rb_Scopus.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        rb_Scopus.setText("Scopus");
        rb_Scopus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ScopusActionPerformed(evt);
            }
        });

        rb_WoS.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        rb_WoS.setText("WoS/ESCI");
        rb_WoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_WoSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(archSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Inicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                                .addComponent(Cancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_Scopus)
                                    .addComponent(rb_WoS))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(rb_Scopus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_WoS)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inicio)
                    .addComponent(Cancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        label1.getAccessibleContext().setAccessibleName("Archivo Seleccionado");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Si se le da a cancelar ,vuelve a abrir la ventana de seleccionar archivo
     * @param evt
     * 
     */
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
        Abrir abrir = new Abrir();
    }//GEN-LAST:event_CancelarActionPerformed
    
    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        try {
            inicio();
        } catch (IOException ex) {
            Logger.getLogger(TipoArchivoSelec.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InicioActionPerformed

    private void rb_ScopusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ScopusActionPerformed
        if(rb_WoS.isSelected()){
            rb_WoS.setSelected(false);
        }
    }//GEN-LAST:event_rb_ScopusActionPerformed

    private void rb_WoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_WoSActionPerformed
        if(rb_Scopus.isSelected()){
            rb_Scopus.setSelected(false);
        }
    }//GEN-LAST:event_rb_WoSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoArchivoSelec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoArchivoSelec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoArchivoSelec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoArchivoSelec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoArchivoSelec().setVisible(true);
            }
        });
        
    }
    private void inicio() throws IOException{
        
//       Aqui se valida que el usuario seleccione algun tipo de de Excel
        if(!rb_Scopus.isSelected()&&!rb_WoS.isSelected()){
            JOptionPane.showMessageDialog(null, "Seleccione un tipo de archivo","Tipo de archivo",JOptionPane.ERROR_MESSAGE);
        }else{
            
            Excel ex = new Excel();
            //Cierra esta ventana
            dispose();
            //ventana donde se ven la informacion no reconocida
            Conflictos conflic=new Conflictos(ex);
            //Procesa el archivo

            conflic.setTitle("Conflictos encontrados");
            //Tipo de Excel 
            Documento doc;
            if(rb_Scopus.isSelected()){
                doc=Documento.scopus;
            }else{//tambien web of sciense
                doc=Documento.WoS;
            }
            //ventana donde se ve la barra de progreso
            Cargando cargando = new Cargando();
            cargando.setVisible(true);
            Runnable runnable = new Runnable() {
               @Override
               public void run() {
                //Llama al metodo que procesa el excel y saca la informacion solicitada 
                ex.Importar(Archivo,conflic.getjTable1(),doc);
                cargando.dispose();
//                La ventana de conflictos se ve despues de que termina de procesar el excel
                conflic.setVisible(true);
               }
            };

            Thread hilo=new Thread(runnable);
            hilo.start();       
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Inicio;
    private java.awt.Label archSelect;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private java.awt.Label label1;
    private javax.swing.JRadioButton rb_Scopus;
    private javax.swing.JRadioButton rb_WoS;
    // End of variables declaration//GEN-END:variables
    
    public Label getArchSelect() {
        return archSelect;
    }


     

}
